### ISSUE TITLE
InternalConfigProvider fails - cp-server-connect:6.2.0

### ISSUE THREAD

**Issue by vikshab** [confluentinc/kafka-images#121]
We have a Confluent Connect cluster running in k8s, and AWS MSK for our Kafka.
We are trying to enable InternalConfigProvider for externalizing secrets in Connect cluster and running into issues.
We enabled our MSK cluster with SASL_SSL (AWS_MSK_IAM as mechanism).

Here are the properties we set in the worker configuration to enable InternalConfigProvider: 
```
...
 {name: "config.providers", value: "secret"},
 {name: "config.providers.secret.class",value: "io.confluent.connect.secretregistry.rbac.config.provider.InternalSecretConfigProvider"},
  {
      name: "config.providers.secret.param.master.encryption.key",
      valueFrom: {
          secretKeyRef: {
              name: args.secret.metadata.name,
              key: "masterEncryptionKey"
          }
      }
  },
{name: "config.providers.secret.param.rest.extension.classes", value: "io.confluent.connect.security.ConnectSecurityExtension,io.confluent.connect.secretregistry.ConnectSecretRegistryExtension"},
{name: "config.providers.secret.param.kafkastore.bootstrap.servers", value: args.bootstrapServers},
{name: "config.providers.secret.param.kafkastore.security.protocol", value: "SASL_SSL"},
{name: "config.providers.secret.param.kafkastore.sasl.mechanism", value: "AWS_MSK_IAM"},
{name: "config.providers.secret.param.kafkastore.sasl.jaas.config", value: "software.amazon.msk.auth.iam.IAMLoginModule required;"},
{name: "config.providers.secret.param.kafkastore.sasl.login.callback.handler.class" ,value: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"},
```

However, Kafka Connect fails to initialize SecretRegistry with the error below:
```
2021-11-15 19:25:14,442 INFO  : SecretRegistryConfig values:
	access.control.allow.headers =
	access.control.allow.methods =
	access.control.allow.origin =
	access.control.skip.options = true
	authentication.method = NONE
	authentication.realm =
	authentication.roles = [*]
	authentication.skip.paths = []
	compression.enable = true
	csrf.prevention.enable = false
	csrf.prevention.token.endpoint = /csrf
	csrf.prevention.token.expiration.minutes = 30
	csrf.prevention.token.max.entries = 10000
	debug = false
	host.name = connect
	idle.timeout.ms = 30000
	inter.instance.headers.whitelist = []
	inter.instance.protocol = http
	kafkastore.bootstrap.servers = ****:9098
	kafkastore.group.id = connect-secret-registry
	kafkastore.init.timeout.ms = 60000
	kafkastore.sasl.kerberos.kinit.cmd = /usr/bin/kinit
	kafkastore.sasl.kerberos.min.time.before.relogin = 60000
	kafkastore.sasl.kerberos.service.name =
	kafkastore.sasl.kerberos.ticket.renew.jitter = 0.05
	kafkastore.sasl.kerberos.ticket.renew.window.factor = 0.8
	kafkastore.sasl.mechanism = AWS_MSK_IAM
	kafkastore.security.protocol = SASL_SSL
	kafkastore.ssl.cipher.suites =
	kafkastore.ssl.enabled.protocols = TLSv1.2,TLSv1.1,TLSv1
	kafkastore.ssl.endpoint.identification.algorithm =
	kafkastore.ssl.key.password = [hidden]
	kafkastore.ssl.keymanager.algorithm = SunX509
	kafkastore.ssl.keystore.location =
	kafkastore.ssl.keystore.password = [hidden]
	kafkastore.ssl.keystore.type = JKS
	kafkastore.ssl.protocol = TLS
	kafkastore.ssl.provider =
	kafkastore.ssl.trustmanager.algorithm = PKIX
	kafkastore.ssl.truststore.location =
	kafkastore.ssl.truststore.password = [hidden]
	kafkastore.ssl.truststore.type = JKS
	kafkastore.timeout.ms = 500
	kafkastore.topic = _confluent-secrets
	kafkastore.topic.replication.factor = 3
	listeners = []
	master.eligibility = true
	master.encryption.key = [hidden]
	master.encryption.old.key = null
	metric.reporters = []
	metrics.jmx.prefix = kafka.secret.registry
	metrics.num.samples = 2
	metrics.sample.window.ms = 30000
	metrics.tag.map = []
	port = 8081
	request.logger.name = io.confluent.rest-utils.requests
	request.queue.capacity = 2147483647
	request.queue.capacity.growby = 64
	request.queue.capacity.init = 128
	resource.extension.class = []
	resource.extension.classes = []
	resource.static.locations = []
	response.http.headers.config =
	response.mediatype.default = application/vnd.secretregistry.v1+json
	response.mediatype.preferred = [application/vnd.secretregistry.v1+json, application/vnd.secretregistry+json, application/json]
	rest.servlet.initializor.classes = []
	secret.registry.group.id = connect-secret-registry
	shutdown.graceful.ms = 1000
	ssl.cipher.suites = []
	ssl.client.auth = false
	ssl.client.authentication = NONE
	ssl.enabled.protocols = []
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = [hidden]
	ssl.keymanager.algorithm =
	ssl.keystore.location =
	ssl.keystore.password = [hidden]
	ssl.keystore.reload = false
	ssl.keystore.type = JKS
	ssl.keystore.watch.location =
	ssl.protocol = TLS
	ssl.provider =
	ssl.trustmanager.algorithm =
	ssl.truststore.location =
	ssl.truststore.password = [hidden]
	ssl.truststore.type = JKS
	thread.pool.max = 200
	thread.pool.min = 8
	websocket.path.prefix = /ws
	websocket.servlet.initializor.classes = []
 (io.confluent.kafka.secretregistry.rest.SecretRegistryConfig)
2021-11-15 19:25:14,442 INFO  : Initializing KafkaStore with broker endpoints: SASL_SSL:// ***:9098,SASL_SSL:// ***:9098,SASL_SSL:// ***:9098 (io.confluent.kafka.secretregistry.storage.KafkaStore)
2021-11-15 19:25:14,839 INFO  : AdminClientConfig values:
	bootstrap.servers = [SASL_SSL://***:9098, SASL_SSL://***9098, SASL_SSL://***:9098]
	client.dns.lookup = use_all_dns_ips
	client.id =
	connections.max.idle.ms = 300000
	default.api.timeout.ms = 60000
	host.resolver.class = class org.apache.kafka.clients.DefaultHostResolver
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = class software.amazon.msk.auth.iam.IAMClientCallbackHandler
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = AWS_MSK_IAM
	security.protocol = SASL_SSL
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
 (org.apache.kafka.clients.admin.AdminClientConfig)
2021-11-15 19:25:14,843 INFO  : Successfully logged in. (org.apache.kafka.common.security.authenticator.AbstractLogin)
2021-11-15 19:25:14,940 WARN  : The configuration 'group.id' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig)
2021-11-15 19:25:14,940 INFO  : Kafka version: 6.2.0-ce (org.apache.kafka.common.utils.AppInfoParser)
2021-11-15 19:25:14,940 INFO  : Kafka commitId: 5c753752ae1445a1 (org.apache.kafka.common.utils.AppInfoParser)
2021-11-15 19:25:14,940 INFO  : Kafka startTimeMs: 1637004314940 (org.apache.kafka.common.utils.AppInfoParser)
2021-11-15 19:25:15,240 INFO  : [AdminClient clientId=adminclient-16] Failed authentication with b-1.kafka-dev-2a49435.21n8jj.c19.kafka.us-east-1.amazonaws.com/10.10.6.74 (errorMessage=An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: Exception while evaluating challenge [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]) occurred when evaluating SASL token received from the Kafka Broker. Kafka Client will go to AUTHENTICATION_FAILED state. caused by Exception while evaluating challenge) (org.apache.kafka.common.network.Selector)
2021-11-15 19:25:15,245 ERROR : [AdminClient clientId=adminclient-16] Connection to node -1 (***.us-east-1.amazonaws.com/10.10.6.74:9098) failed authentication due to: An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: Exception while evaluating challenge [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]) occurred when evaluating SASL token received from the Kafka Broker. Kafka Client will go to AUTHENTICATION_FAILED state. (org.apache.kafka.clients.NetworkClient)
2021-11-15 19:25:15,245 WARN  : [AdminClient clientId=adminclient-16] Metadata update failed due to authentication error (org.apache.kafka.clients.admin.internals.AdminMetadataManager)
org.apache.kafka.common.errors.SaslAuthenticationException: An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: Exception while evaluating challenge [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]) occurred when evaluating SASL token received from the Kafka Broker. Kafka Client will go to AUTHENTICATION_FAILED state.
Caused by: javax.security.sasl.SaslException: Exception while evaluating challenge [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:113)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:540)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:540)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:439)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:333)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:274)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:247)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:499)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:639)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1379)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1310)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback
	at org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.handle(SaslClientCallbackHandler.java:98)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.generateClientMessage(IAMSaslClient.java:138)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:95)
	... 14 more
2021-11-15 19:25:15,342 INFO  : App info kafka.admin.client for adminclient-16 unregistered (org.apache.kafka.common.utils.AppInfoParser)
2021-11-15 19:25:15,342 INFO  : [AdminClient clientId=adminclient-16] Metadata update failed (org.apache.kafka.clients.admin.internals.AdminMetadataManager)
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1637004344943, tries=1, nextAllowedTryMs=-9223372036854775709) timed out at 9223372036854775807 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2021-11-15 19:25:15,342 INFO  : [AdminClient clientId=adminclient-16] Metadata update failed (org.apache.kafka.clients.admin.internals.AdminMetadataManager)
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1637004345245, tries=1, nextAllowedTryMs=-9223372036854775709) timed out at 9223372036854775807 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2021-11-15 19:25:15,343 INFO  : Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics)
2021-11-15 19:25:15,343 INFO  : Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics)
2021-11-15 19:25:15,344 INFO  : Metrics reporters closed (org.apache.kafka.common.metrics.Metrics)
2021-11-15 19:25:15,344 WARN  : Error initializing InternalSecretConfigProvider (io.confluent.connect.secretregistry.rbac.config.provider.InternalSecretConfigProvider)
io.confluent.kafka.secretregistry.exceptions.SecretRegistryInitializationException: Error initializing kafka store while initializing secret registry
	at io.confluent.kafka.secretregistry.storage.KafkaSecretRegistry.initStore(KafkaSecretRegistry.java:150)
	at io.confluent.connect.secretregistry.rbac.config.provider.InternalSecretConfigProvider.initSecretRegistry(InternalSecretConfigProvider.java:59)
	at io.confluent.connect.secretregistry.rbac.config.provider.InternalSecretConfigProvider.configure(InternalSecretConfigProvider.java:70)
	at org.apache.kafka.common.config.AbstractConfig.instantiateConfigProviders(AbstractConfig.java:572)
	at org.apache.kafka.common.config.AbstractConfig.resolveConfigVariables(AbstractConfig.java:515)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:107)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129)
	at org.apache.kafka.clients.consumer.ConsumerConfig.<init>(ConsumerConfig.java:640)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:667)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:615)
	at org.apache.kafka.connect.util.KafkaBasedLog.createConsumer(KafkaBasedLog.java:352)
	at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:196)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.start(KafkaConfigBackingStore.java:278)
	at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:130)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:310)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.confluent.kafka.secretregistry.storage.exceptions.StoreInitializationException: Failed trying to create or validate secret topic configuration
	at io.confluent.kafka.secretregistry.storage.KafkaStore.createOrVerifySecretTopic(KafkaStore.java:170)
	at io.confluent.kafka.secretregistry.storage.KafkaStore.init(KafkaStore.java:108)
	at io.confluent.kafka.secretregistry.storage.KafkaSecretRegistry.initStore(KafkaSecretRegistry.java:147)
	... 19 more
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.SaslAuthenticationException: An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: Exception while evaluating challenge [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]) occurred when evaluating SASL token received from the Kafka Broker. Kafka Client will go to AUTHENTICATION_FAILED state.
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:104)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
	at io.confluent.kafka.secretregistry.storage.KafkaStore.createOrVerifySecretTopic(KafkaStore.java:158)
	... 21 more
Caused by: org.apache.kafka.common.errors.SaslAuthenticationException: An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: Exception while evaluating challenge [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]) occurred when evaluating SASL token received from the Kafka Broker. Kafka Client will go to AUTHENTICATION_FAILED state.
Caused by: javax.security.sasl.SaslException: Exception while evaluating challenge [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:113)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:540)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:423)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:540)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:439)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:333)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:274)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:247)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:563)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:499)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:639)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1379)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1310)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback
	at org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.handle(SaslClientCallbackHandler.java:98)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.generateClientMessage(IAMSaslClient.java:138)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:95)
	... 14 more
```
If I remove these properties from the worker configuration, the cluster works as expected.

**Comment by vikshab** [comment]
It looks like  `UnsupportedCallbackException` was mentioned in the` aws-mks-iam-auth` lib Readme file: https://github.com/aws/aws-msk-iam-auth#kafka-connect-unsupported-callback-type

I followed the recommendation, and put `aws-msk-iam-auth-1.1.0.jar` under the JVM classpath `/usr/share/java/cp-base-new/` (tried also `/etc/kafka-connect/jars/`), and set up `plugin.path=/usr/share/confluent-hub-components`. I was still getting the error, but slight different 
```
org.apache.kafka.common.config.ConfigException: Invalid value software.amazon.msk.auth.iam.IAMClientCallbackHandler for configuration sasl.login.callback.handler.class: Class software.amazon.msk.auth.iam.IAMClientCallbackHandler could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:758)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:504)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:497)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:113)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:146)
	at org.apache.kafka.clients.admin.AdminClientConfig.<init>(AdminClientConfig.java:241)
	at org.apache.kafka.clients.admin.Admin.create(Admin.java:133)
	at org.apache.kafka.clients.admin.AdminClient.create(AdminClient.java:39)
	at io.confluent.kafka.secretregistry.storage.KafkaStore.createOrVerifySecretTopic(KafkaStore.java:156)
	at io.confluent.kafka.secretregistry.storage.KafkaStore.init(KafkaStore.java:108)
	at io.confluent.kafka.secretregistry.storage.KafkaSecretRegistry.initStore(KafkaSecretRegistry.java:147)
	at io.confluent.connect.secretregistry.rbac.config.provider.InternalSecretConfigProvider.initSecretRegistry(InternalSecretConfigProvider.java:59)
	at io.confluent.connect.secretregistry.rbac.config.provider.InternalSecretConfigProvider.configure(InternalSecretConfigProvider.java:70)
	at org.apache.kafka.common.config.AbstractConfig.instantiateConfigProviders(AbstractConfig.java:576)
	at org.apache.kafka.common.config.AbstractConfig.resolveConfigVariables(AbstractConfig.java:519)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:112)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:133)
	at org.apache.kafka.connect.runtime.WorkerConfig.<init>(WorkerConfig.java:400)
	at org.apache.kafka.connect.runtime.distributed.DistributedConfig.<init>(DistributedConfig.java:417)
	at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:94)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:79)
2021-11-19 19:29:32,740 ERROR : Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed)
org.apache.kafka.common.config.ConfigException: Invalid value software.amazon.msk.auth.iam.IAMClientCallbackHandler for configuration sasl.client.callback.handler.class: Class software.amazon.msk.auth.iam.IAMClientCallbackHandler could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:758)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:504)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:497)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:113)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:133)
	at org.apache.kafka.connect.runtime.WorkerConfig.<init>(WorkerConfig.java:400)
	at org.apache.kafka.connect.runtime.distributed.DistributedConfig.<init>(DistributedConfig.java:417)
	at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:94)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:79)

```

**Comment by tooptoop4** [comment]
@vikshab did u solve?

**Comment by vikshab** [comment]
> InternalConfigProvider

Unfortunately not. I might return to this issue again. We decided to use AwsSecretsConfigProvider instead
