### ISSUE TITLE
Unable to use transactional producer against cp-kafka:7.5.0

### ISSUE THREAD

**Issue by paul-feuer** [confluentinc/kafka-images#259]
We're trying to launch a single-node cluster in our CICD integration test environment. In this environment, we expect to run services which use transactions and EOS. We also are using cp-schema-registry:7.5.0. We have currently 1 producer using transactions using aiokafka, and 2 using java streams 3.5.0 (with java17)

when committing a transaction from either the python aiokafka producer or a java KafkaProducer (to see if this behavior occurs outside of the streams), the broker immediately logs errors and starts consuming 99% of CPU. It prints the following in the output (this particular one was from a java KafkaProducer)

```
[2024-02-01 23:21:31,425] INFO [TransactionCoordinator id=1] Initialized transactionalId b6e72b63-2b98-4fa1-a0e9-b0e8a988c3fc with producerId 0 and producer epoch 0 on partition __transaction_state-49 (kafka.coordinator.transaction.TransactionCoordinator)
[2024-02-01 23:21:40,522] ERROR Closing socket for 127.0.0.1:29093-127.0.0.1:55464-0 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Received request api key WRITE_TXN_MARKERS with version 1 which is not enabled
[2024-02-01 23:21:40,526] INFO [TransactionCoordinator id=1] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2024-02-01 23:21:40,526] ERROR Exception while processing request from 127.0.0.1:29093-127.0.0.1:55464-0 (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Received request api key WRITE_TXN_MARKERS with version 1 which is not enabled
[2024-02-01 23:21:40,527] INFO [TransactionCoordinator id=1] Cancelled in-flight WRITE_TXN_MARKERS request with correlation id 0 due to node 1 being disconnected (elapsed time since creation: 12ms, elapsed time since send: 7ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
[2024-02-01 23:21:40,578] ERROR Closing socket for 127.0.0.1:29093-127.0.0.1:55478-1 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Received request api key WRITE_TXN_MARKERS with version 1 which is not enabled
[2024-02-01 23:21:40,578] ERROR Exception while processing request from 127.0.0.1:29093-127.0.0.1:55478-1 (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Received request api key WRITE_TXN_MARKERS with version 1 which is not enabled
[2024-02-01 23:21:40,578] INFO [TransactionCoordinator id=1] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2024-02-01 23:21:40,578] INFO [TransactionCoordinator id=1] Cancelled in-flight WRITE_TXN_MARKERS request with correlation id 86 due to node 1 being disconnected (elapsed time since creation: 1ms, elapsed time since send: 0ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient)
```

it prints this same series of batch messages (with different correlation ids) about every 50ms or 100ms (seems to move between the two).

our kubernetes node in the CICD contains the following environment variables:
```
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:29093,PLAINTEXT_HOST://${PREFIX}-kafka${TLD}:9092
      - KAFKA_JMX_PORT=9101
      - KAFKA_JMX_HOSTNAME=${PREFIX}-kafka${TLD}
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:29093
      - KAFKA_LISTENERS=PLAINTEXT://:29092,CONTROLLER://:29093,PLAINTEXT_HOST://:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
```

the schema registry seems to be fine and creates its topic and records registered schemas. part of our startup process also uses a python admin client to create and configure some topics and that works. the streams services create their state store topics. all the producers are able to initTransactions. it's just when one of the producers attempts to commit a transaction, the broker goes into this mode.

**Comment by paul-feuer** [comment]
I forgot to mention the apps run fine against a 3-broker cluster running kafka_2.13-3.4.0 and a 10 node cluster (not sure what version that cluster is)

**Comment by paul-feuer** [comment]
adding the DEBUG to the logging via KAFKA_LOG4J_ROOT_LOGLEVEL=DEBUG

also happens against 7.5.3

```
[2024-02-02 17:41:42,132] DEBUG [QuorumController id=1] Processed handleCommit[baseOffset=282] in 140 us (org.apache.kafka.controller.QuorumController)
[2024-02-02 17:41:42,304] DEBUG Resolved host localhost as 127.0.0.1 (org.apache.kafka.clients.ClientUtils)
[2024-02-02 17:41:42,304] DEBUG [TransactionCoordinator id=1] Initiating connection to node localhost:29093 (id: 1 rack: null) using address localhost/127.0.0.1 (org.apache.kafka.clients.NetworkClient)
[2024-02-02 17:41:42,305] DEBUG [TransactionCoordinator id=1] Created socket with SO_RCVBUF = 102400, SO_SNDBUF = 2097152, SO_TIMEOUT = 0 to node 1 (org.apache.kafka.common.network.Selector)
[2024-02-02 17:41:42,305] DEBUG [TransactionCoordinator id=1] Completed connection to node 1. Ready. (org.apache.kafka.clients.NetworkClient)
[2024-02-02 17:41:42,305] DEBUG [TransactionCoordinator id=1] Sending WRITE_TXN_MARKERS request with header RequestHeader(apiKey=WRITE_TXN_MARKERS, apiVersion=1, clientId=broker-1-txn-marker-sender, correlationId=0, headerVersion=2) and timeout 30000 to node 1: WriteTxnMarkersRequestData(markers=[WritableTxnMarker(producerId=0, producerEpoch=0, transactionResult=true, topics=[WritableTxnMarkerTopic(name='my-topic', partitionIndexes=[0])], coordinatorEpoch=0)]) (org.apache.kafka.clients.NetworkClient)
[2024-02-02 17:41:42,341] ERROR Closing socket for 127.0.0.1:29093-127.0.0.1:56526-0 because of error (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Received request api key WRITE_TXN_MARKERS with version 1 which is not enabled
[2024-02-02 17:41:42,343] DEBUG [TransactionCoordinator id=1] Connection with localhost/127.0.0.1 (channelId=1) disconnected (org.apache.kafka.common.network.Selector)
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:86)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)
        at kafka.common.InterBrokerSendThread.pollOnce(InterBrokerSendThread.scala:78)
        at kafka.common.InterBrokerSendThread.doWork(InterBrokerSendThread.scala:98)
        at org.apache.kafka.server.util.ShutdownableThread.run(ShutdownableThread.java:127)
[2024-02-02 17:41:42,344] INFO [TransactionCoordinator id=1] Node 1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2024-02-02 17:41:42,344] ERROR Exception while processing request from 127.0.0.1:29093-127.0.0.1:56526-0 (kafka.network.Processor)
org.apache.kafka.common.errors.InvalidRequestException: Received request api key WRITE_TXN_MARKERS with version 1 which is not enabled
[2024-02-02 17:41:42,346] DEBUG [TransactionCoordinator id=1] Cancelled in-flight WRITE_TXN_MARKERS request with correlation id 0 due to node 1 being disconnected (elapsed time since creation: 43ms, elapsed time since send: 39ms, request timeout: 30000ms): WriteTxnMarkersRequestData(markers=[WritableTxnMarker(producerId=0, producerEpoch=0, transactionResult=true, topics=[WritableTxnMarkerTopic(name='my-topic, partitionIndexes=[0])], coordinatorEpoch=0)]) (org.apache.kafka.clients.NetworkClient)

**Comment by paul-feuer** [comment]
and a small producer example to reproduce:
```
import java.util.List;
import java.util.Properties;
import java.util.UUID;
import org.apache.kafka.clients.admin.AdminClient;
import org.apache.kafka.clients.admin.NewTopic;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.common.serialization.StringSerializer;

public class SendMessage {
  private static final String TOPIC = "my-topic";
  private static final String BOOTSTRAP = "my-kafka.my-namespace:9092";

  private static final boolean USE_TX = true;

  public static void main(String[] args) {
    final Properties props = new Properties();
    props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, BOOTSTRAP);
    System.out.println("Creating admin client");
    try (var admin = AdminClient.create(props)) {
      final var result = admin.createTopics(List.of(new NewTopic(TOPIC, 1, (short) 1)));
      result.all().get();
      System.out.println("Created topic");
    } catch (Exception ex) {
      System.out.printf("Did not create topic: %s%n", ex.getMessage());
    }
    if (USE_TX) {
      props.put(ProducerConfig.TRANSACTIONAL_ID_CONFIG, UUID.randomUUID().toString());
    }
    props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
    props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
    System.out.println("Creating producer");
    try (Producer<String, String> producer = new KafkaProducer<>(props)) {
      if (USE_TX) {
        producer.initTransactions();
        producer.beginTransaction();
      }
      producer.send(
          new ProducerRecord<>(TOPIC, "a-key", "a-value"),
          (meta, ex) -> {
            if (ex != null) {
              System.out.printf("sent message with exception: %s%n", ex.getMessage());
            } else {
              System.out.printf("sent message with offset: %s%n", meta.offset());
            }
          });
      if (USE_TX) {
        producer.commitTransaction();
      } else {
        producer.flush();
      }
    }
  }
}

```

**Comment by paul-feuer** [comment]
ok - was a problem with listener names

before i figured it out, i tried this configuration. the behavior of the rapid, cpu-intensive logging went away, but the transactions would not get committed:
```
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=BROKER://${PREFIX}-kafka${TLD}:9092
      - KAFKA_JMX_PORT=9101
      - KAFKA_JMX_HOSTNAME=${PREFIX}-kafka${TLD}
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9094
      - KAFKA_LISTENERS=BROKER://:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=BROKER
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_LOG4J_ROOT_LOGLEVEL=DEBUG
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=1
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
```
it would attempt to contact the TransactionCoordinator using the FQDN, but would not complete the transaction.

I added a third listener in the following config, and then it worked.
```
- KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,BROKER:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://localhost:29092,BROKER://${PREFIX}-kafka${TLD}:9092
      - KAFKA_JMX_PORT=9101
      - KAFKA_JMX_HOSTNAME=${PREFIX}-kafka${TLD}
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9094
      - KAFKA_LISTENERS=INTERNAL://:29092,CONTROLLER://:9094,BROKER://:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_MIN_INSYNC_REPLICAS=1
      - KAFKA_LOG4J_ROOT_LOGLEVEL=TRACE
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS=1
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
```
then it was able to commit the transaction properly.

A couple of takeaways for me, wrt to the broker are:
- how is such misconfiguration allowed? e.g. it seems that if you configure the broker to connect to a controller for transactions, it should fail pretty clearly as opposed to the controller just saying "hey, you know i don't support transactions", which is what it seems like is happening
- it's unclear to me also why there would be a difference in managing the transaction between two listeners on the same broker. and additionally, tho maybe not necessary, why the broker needs to contact the transaction coordinator for the partition over a network connection, when the instance is itself the coordinator.
