### ISSUE TITLE
MSK connection using IAM authentication is lost when produce event of mysql table data

### ISSUE THREAD

**Issue by comstering** [confluentinc/kafka-images#359]
Hi!!
I'm building kafka connect to AWS MSK using the Confluent Kafka image.
I'd like to produce CDC data.
I fancing some issues.

My environment
Kafka Broker: AWS MSK
Kafka Connect: AWS EKS k8s container
Broker Authentication: SASL_SSL, AWS_MSK_IAM

My successful step
1. The Kafka Connect container sussessfully cunnects AWS MSK.
    - Successfully produced configuration topics: `config.storage.topic`, `offset.storage.topic`, and `status.storage.topic`
2. Register the MySQL connector plugin (Debezium)
    - Successfully produced the `schema.history topic`.
    - Connector Configuration

```
{
  "name": "debezium-mysql-connector-first",
  "connector.class": "io.debezium.connector.mysql.MySqlConnector",
  "tasks.max": 1,

  "database.hostname": {database.endpoint},
  "database.user": {username},
  "database.password": {password},
  "topic.prefix": "debeziumfirst",
  "database.server.id": 100001,
  "table.include.list": {database.table},

  "snapshot.mode": "when_needed",
  "snapshot.locking.mode": "none",

  "schema.history.internal.kafka.topic": "schemahistory.debeziumfirst",
  "schema.history.internal.kafka.bootstrap.servers": "{AWS_MSK_BROKERS}",
  "schema.history.internal.producer.security.protocol": "SASL_SSL",
  "schema.history.internal.consumer.security.protocol": "SASL_SSL",
  "schema.history.internal.producer.sasl.mechanism": "AWS_MSK_IAM",
  "schema.history.internal.consumer.sasl.mechanism": "AWS_MSK_IAM",
  "schema.history.internal.producer.sasl.jaas.config": "software.amazon.msk.auth.iam.IAMLoginModule required;",
  "schema.history.internal.consumer.sasl.jaas.config": "software.amazon.msk.auth.iam.IAMLoginModule required;",
  "schema.history.internal.producer.sasl.client.callback.handler.class": "software.amazon.msk.auth.iam.IAMClientCallbackHandler",
  "schema.history.internal.consumer.sasl.client.callback.handler.class": "software.amazon.msk.auth.iam.IAMClientCallbackHandler",

  "key.converter": "org.apache.kafka.connect.json.JsonConverter",
  "value.converter": "org.apache.kafka.connect.json.JsonConverter",
  "key.converter.schemas.enable": false,
  "value.converter.schemas.enable": false,

  "errors.log.enable": true,
  "errors.log.include.messages": true
}
```

- Here is topic list
<img width="1451" alt="스크린샷 2024-10-16 오후 10 31 47" src="https://github.com/user-attachments/assets/991e9e34-b95a-41ba-9d25-9fe8e584f194">

### My Problem
I register MySQL connector.
Successfully produced `schema.history` topic.
**But failed to produce MySQL cdc table data.**

How can I fix?

Here is the Connect log.
```
[2024-10-16 13:38:18,219] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Initialize connection to node b-1.hansumsk.yrpuyf.c2.kafka.ap-northeast-2.amazonaws.com:9098 (id: -2 rack: null) for sending telemetry request (org.apache.kafka.clients.NetworkClient)
[2024-10-16 13:38:18,219] DEBUG Resolved host b-1.hansumsk.yrpuyf.c2.kafka.ap-northeast-2.amazonaws.com as 10.0.43.162 (org.apache.kafka.clients.ClientUtils)
[2024-10-16 13:38:18,219] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Resolved host b-1.hansumsk.yrpuyf.c2.kafka.ap-northeast-2.amazonaws.com to addresses [b-1.hansumsk.yrpuyf.c2.kafka.ap-northeast-2.amazonaws.com/10.0.43.162] (org.apache.kafka.clients.ClusterConnectionStates)
[2024-10-16 13:38:18,219] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Initiating connection to node b-1.hansumsk.yrpuyf.c2.kafka.ap-northeast-2.amazonaws.com:9098 (id: -2 rack: null) using address b-1.hansumsk.yrpuyf.c2.kafka.ap-northeast-2.amazonaws.com/10.0.43.162 (org.apache.kafka.clients.NetworkClient)
[2024-10-16 13:38:18,221] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 131072, SO_TIMEOUT = 0 to node -2 (org.apache.kafka.common.network.Selector)
[2024-10-16 13:38:18,221] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Completed connection to node -2. Fetching API versions. (org.apache.kafka.clients.NetworkClient)
[2024-10-16 13:38:18,221] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Initiating API versions fetch from node -2. (org.apache.kafka.clients.NetworkClient)
[2024-10-16 13:38:18,221] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Sending API_VERSIONS request with header RequestHeader(apiKey=API_VERSIONS, apiVersion=3, clientId=connector-producer-debezium-mysql-connector-first-0, correlationId=7185, headerVersion=2) and timeout 30000 to node -2: ApiVersionsRequestData(clientSoftwareName='apache-kafka-java', clientSoftwareVersion='7.7.0-ccs') (org.apache.kafka.clients.NetworkClient)
[2024-10-16 13:38:18,231] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Connection with b-1.hansumsk.yrpuyf.c2.kafka.ap-northeast-2.amazonaws.com/10.0.43.162 (channelId=-2) disconnected (org.apache.kafka.common.network.Selector)
java.io.EOFException
    at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:109)
    at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
    at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
    at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
    at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
    at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
    at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:585)
    at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:351)
    at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:253)
    at java.base/java.lang.Thread.run(Thread.java:840)
[2024-10-16 13:38:18,231] INFO [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Node -2 disconnected. (org.apache.kafka.clients.NetworkClient)
[2024-10-16 13:38:18,231] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Cancelled in-flight API_VERSIONS request with correlation id 7185 due to node -2 being disconnected (elapsed time since creation: 10ms, elapsed time since send: 10ms, request timeout: 30000ms): ApiVersionsRequestData(clientSoftwareName='apache-kafka-java', clientSoftwareVersion='7.7.0-ccs') (org.apache.kafka.clients.NetworkClient)
[2024-10-16 13:38:18,231] WARN [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Bootstrap broker b-1.hansumsk.yrpuyf.c2.kafka.ap-northeast-2.amazonaws.com:9098 (id: -2 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2024-10-16 13:38:18,231] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Give up sending telemetry request since no node is available (org.apache.kafka.clients.NetworkClient)
[2024-10-16 13:38:18,282] DEBUG [Producer clientId=connector-producer-debezium-mysql-connector-first-0] Give up sending telemetry request since no node is available (org.apache.kafka.clients.NetworkClient)

```

And the AWS MSK log at CloudWatch

<img width="1579" alt="스크린샷 2024-10-16 오후 10 37 08" src="https://github.com/user-attachments/assets/3bc56051-7f58-4ad7-8c7b-bffe727b89b8">

**Comment by comstering** [comment]
I solved this issue.

I add env value

```
CONNECT_PRODUCER_SECURITY_PROTOCOL: "SASL_SSL"
CONNECT_PRODUCER_SASL_MECHANISM: "AWS_MSK_IAM"
CONNECT_PRODUCER_SASL_JAAS_CONFIG: "software.amazon.msk.auth.iam.IAMLoginModule required;"
CONNECT_PRODUCER_SASL_CLIENT_CALLBACK_HANDLER_CLASS: "software.amazon.msk.auth.iam.IAMClientCallbackHandler"
```

Thank you..!
