### ISSUE TITLE
cp-kafka cluster got stuck after enable SASL/PLAIN 

### ISSUE THREAD

**Issue by cobolbaby** [confluentinc/kafka-images#64]
If SASL authentication  mechanism is enabled, the replication synchronization between Kafka clusters will be abnormal. 

Exception stack:

```
WARN [ReplicaFetcher replicaId=3, leaderId=2, fetcherId=0] Error in response for fetch request (type=FetchRequest, replicaId=3, maxWait=500, minBytes=1, maxBytes=10485760．．．
java.io.IOException: Connection to 2 was disconnected before the response was read
	at org.apache.kafka.clients.NetworkClientUtils.sendAndReceive(NetworkClientUtils.java:100)
	at kafka.server.ReplicaFetcherBlockingSend.sendRequest(ReplicaFetcherBlockingSend.scala:108)
	at kafka.server.ReplicaFetcherThread.fetchFromLeader(ReplicaFetcherThread.scala:206)
	at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:304)
	at kafka.server.AbstractFetcherThread.$anonfun$maybeFetch$3(AbstractFetcherThread.scala:137)
	at kafka.server.AbstractFetcherThread.maybeFetch(AbstractFetcherThread.scala:136)
	at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:119)
	at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:96)
```

**Comment by cobolbaby** [comment]
If SASL is enabled, will it affect the existing data directories?

**Comment by cobolbaby** [comment]
It seems that the time of commit offset will exceed the default timeout configuration.

**Comment by cobolbaby** [comment]
RC: The JBDC client may encounter DNS resolution problems after SASL authentication is configured.

**Comment by cobolbaby** [comment]
Problems caused by host dns.

**Comment by notizklotz** [comment]
I observed the same problem and I could resolve it by advertising the brokers using fully qualified domain names.

If the brokers are avertised by IP adresses this causes a reverse DNS lookup via java.net.InetAddress#getHostName() which is slow on some environments. The relevant code is here: https://github.com/apache/kafka/blob/3.3.1/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java#L231

**Comment by mooc9988** [comment]
> I observed the same problem and I could resolve it by advertising the brokers using fully qualified domain names.
> 
> If the brokers are avertised by IP adresses this causes a reverse DNS lookup via java.net.InetAddress#getHostName() which is slow on some environments. The relevant code is here: https://github.com/apache/kafka/blob/3.3.1/clients/src/main/java/org/apache/kafka/common/network/SaslChannelBuilder.java#L231

Many thanks for your reply. For anyone meeting the same problem, you can use `dig -x {IP}` to test if there is a "a reverse DNS lookup" problem in your environment.
