### ISSUE TITLE
Create a topic on container creation - KAFKA_CREATE_TOPICS env

### ISSUE THREAD

**Issue by aldosilva6** [confluentinc/kafka-images#70]
Is there any way to create a topic when create the kafka container on docker-compose? Because I'm using a spring-boot application and the log show a lot of messages until my first request because the topic has not been created.

cpo-executor     | 19:40:07.978 [kafka-admin-client-thread | adminclient-1] WARN  o.apache.kafka.clients.NetworkClient - [AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
cpo-executor     | 19:40:08.161 [main] ERROR o.s.kafka.core.KafkaAdmin - Could not configure topics
cpo-executor     | org.springframework.kafka.KafkaException: Timed out waiting to get existing topics; nested exception is java.util.concurrent.TimeoutException
cpo-executor     | 	at org.springframework.kafka.core.KafkaAdmin.lambda$checkPartitions$4(KafkaAdmin.java:254)
cpo-executor     | 	at java.util.HashMap.forEach(HashMap.java:1289)
cpo-executor     | 	at org.springframework.kafka.core.KafkaAdmin.checkPartitions(KafkaAdmin.java:233)
cpo-executor     | 	at org.springframework.kafka.core.KafkaAdmin.addTopicsIfNeeded(KafkaAdmin.java:219)
cpo-executor     | 	at org.springframework.kafka.core.KafkaAdmin.initialize(KafkaAdmin.java:189)
cpo-executor     | 	at org.springframework.kafka.core.KafkaAdmin.afterSingletonsInstantiated(KafkaAdmin.java:157)
cpo-executor     | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:963)
cpo-executor     | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923)
cpo-executor     | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
cpo-executor     | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
cpo-executor     | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
cpo-executor     | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
cpo-executor     | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
cpo-executor     | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
cpo-executor     | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
cpo-executor     | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
cpo-executor     | 	at com.closeupinternational.cpoexecutor.CpoExecutorApplication.main(CpoExecutorApplication.java:15)
cpo-executor     | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
cpo-executor     | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
cpo-executor     | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cpo-executor     | 	at java.lang.reflect.Method.invoke(Method.java:498)
cpo-executor     | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
cpo-executor     | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
cpo-executor     | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
cpo-executor     | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
cpo-executor     | Caused by: java.util.concurrent.TimeoutException: null
cpo-executor     | 	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108)
cpo-executor     | 	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272)
cpo-executor     | 	at org.springframework.kafka.core.KafkaAdmin.lambda$checkPartitions$4(KafkaAdmin.java:236)
cpo-executor     | 	... 24 common frames omitted

**Comment by OneCricketeer** [comment]
> I'm using a spring-boot application

You may use `@Bean NewTopic` to create topics rather than depend on the container to do so (which there is no env-var for, and only `wurstmeister/kafka` has it)

**Comment by adamdecaf** [comment]
How would I create topics with this image? We don't manage topics (creation/partitions/etc) in our applications.

**Comment by OneCricketeer** [comment]
@adamdecaf This image doesn't allow it. You'll need to use an external init container, or rewrite the container entrypoint to run topic creation scripts

**Comment by adamdecaf** [comment]
Yea.. That makes this container pretty hard to use in our testing stack. The wurstmeister images don't support ARM machines yet so we're in a tough spot. I've gotten this image to startup but it's SASL config isn't working.
