### ISSUE TITLE
Request failed authentication : cp-kafka-connect:6.1.0-1-ubi8  

### ISSUE THREAD

**Issue by sgandhi123** [confluentinc/kafka-images#71]
Hi, 

My docker setup is as simple as https://github.com/mongodb/mongo-kafka/tree/master/docker. When I try to upgrade base image to 6.1.0-1-ubi8 I am seeing the below debug (exceptions?!) spamming my connect logs. Any help/suggestions are greatly appreciated. Thanks.

-  Broker image version is confluentinc/cp-enterprise-kafka:5.5.0.
-  I am not seeing this for the previous versions.. I've tried versions as latest as 5.5.3-3-ubi8. 
-  This is something to do with the base image since I tried testing even without installing any connectors.

```
[2021-02-11 20:01:40,145] DEBUG Authenticating request (org.apache.kafka.connect.rest.basic.auth.extension.JaasBasicAuthFilter)
[2021-02-11 20:01:40,147] DEBUG Request failed authentication (org.apache.kafka.connect.rest.basic.auth.extension.JaasBasicAuthFilter)
javax.security.auth.login.LoginException: Login Failure: all modules ignored
	at java.base/javax.security.auth.login.LoginContext.invoke(LoginContext.java:871)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:665)
	at java.base/javax.security.auth.login.LoginContext$4.run(LoginContext.java:663)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:663)
	at java.base/javax.security.auth.login.LoginContext.login(LoginContext.java:574)
	at org.apache.kafka.connect.rest.basic.auth.extension.JaasBasicAuthFilter.filter(JaasBasicAuthFilter.java:64)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:108)
	at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:44)
	at org.glassfish.jersey.process.internal.Stages.process(Stages.java:173)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:245)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
```

**Comment by janjwerner-confluent** [comment]
closing this as an old issue.
@sgandhi123 if you're having problems with the latest 5.5.15 please open a new issue.
